@echo off
cls


echo ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
echo ³  Remember to use this file in conjunction with   ³
echo ³  the IPXSETUP.EXE switches.                      ³
echo ³                                                  ³
echo ³  Please refer to the DOOM README.EXE  for more   ³
echo ³  info.                                           ³
echo ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

pause

ipxsetup -file vz4_1-2.wad -DEATHMATCH %1 %2 %3
